services:

  db-task:
    image: lampi-db-task
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      database:
        condition: service_healthy
      s3:
        condition: service_healthy
    environment:
      PG_HOST: "db"
      PG_PORT: "5432"
      DB_NAME: "lampi"
      POSTGRES_USER: "pgadmin"
      POSTGRES_PASSWORD: "pgpassword"
      S3_ENDPOINT: "http://s3:4566"

  database:
    image: postgres:18.1
    container_name: db
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username pgadmin --dbname lampi"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: "pgadmin"
      POSTGRES_PASSWORD: "pgpassword"
      POSTGRES_DB: "lampi"

  s3:
    image: localstack/localstack:4.13
    container_name: s3-local
    ports:
      - "127.0.0.1:4566:4566"
    volumes:
      - ./localstack/init/ready.d:/etc/localstack/init/ready.d
    environment:
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SERVICES=s3
      - DEBUG=1
    healthcheck:
      test: ["CMD-SHELL", "awslocal s3api head-object --bucket oph-lampi-local --key healthcheck.txt"]
      interval: 30s
      timeout: 10s
      retries: 5
